# Generated by Django 4.0.6 on 2022-07-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_student_delete_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='usertype',
        ),
    ]
