# Generated by Django 4.0.6 on 2022-07-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0006_alter_books_title_book_issues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_issues',
        ),
    ]
