# Generated by Django 4.0.6 on 2022-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0009_alter_book_issues_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issues',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
